"""empty message

Revision ID: a3a89571381b
Revises: 856ea492118d
Create Date: 2020-12-12 19:37:09.352399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a89571381b'
down_revision = '856ea492118d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_orders_meals',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('meal_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'meal_id')
    )
    op.drop_table('orders_meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_meals',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meal_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name='orders_meals_meal_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='orders_meals_order_id_fkey')
    )
    op.drop_table('association_orders_meals')
    # ### end Alembic commands ###
